### PR TITLE
Don't override Close. Use Dispose.

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
According to the source code for stream. You should not override `Close` rather all cleanup logic should be called from `Dispose(bool)`.

>Stream used to require that all cleanup logic went into Close(),
which was thought up before we invented IDisposable.  However, we
need to follow the IDisposable pattern so that users can write
sensible subclasses without needing to inspect all their base
classes, and without worrying about version brittleness, from a
base class switching to the Dispose pattern.  We're moving
Stream to the Dispose(bool) pattern - that's where all subclasses
should put their cleanup now.

https://source.dot.net/#System.Private.CoreLib/Stream.cs,284

### CODE REVIEW

**Comment by AraHaan** [comment]
I really need to setup github actions badly here.

**Comment by AraHaan** [comment]
Added the github action, hopefully it works.

**Comment by JimBobSquarePants** [comment]
> Also mind removing the merge commit and instead rebase it?

You can not simply squash the PR when merging?

**Comment by AraHaan** [comment]
I mean I can do that too. Anyways I would like for the CI to run.

**Comment by AraHaan** [comment]
Man I noticed the SixLabors fork of this and I say, the repository structure is great and all and the cleanup of some methods there would help here too.

Mind making a copy of that to place in another pr for here when this is added in?

**Pull request merged**
